[tool.poetry]
name = "magicdb"
version = "0.2.150"
description = ""
authors = ["Jeremy Berman <jerber@sas.upenn.edu>"]
readme = 'README.md'
homepage = 'https://github.com/jerber/magicdb_new'
repository = 'https://github.com/jerber/magicdb_new'
keywords = ['firestore', 'pydantic', 'orm', 'python orm firestore', 'firebase']

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.7.3"
firebase-admin = "^4.4.0"
glom = "^20.8.0"
python-slugify = "^4.0.1"
grpcio = "^1.34.0"
redis = "^3.5.3"
ujson = ">=3.0.0"
phonenumbers = "^8.12.19"
python-google-places = "^1.4.2"
python-dotenv = "^0.15.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

