[tool.poetry]
name = "et_ppMDcommon"
version = "0.4.0"
description = "Tools for the Parallel Programming Course project 2021."
authors = ["Bert Tijskens <engelbert.tijskens@uantwerpen.be>"]
license = "MIT"

readme = 'README.rst'

repository = "https://github.com/etijskens/et_ppMDcommon"
homepage = "https://github.com/etijskens/et_ppMDcommon"

keywords = ['packaging', 'poetry']

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.20.1"
matplotlib = "^3.3.4"

[tool.poetry.dev-dependencies]
pytest = "^4.4.2"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
