[tool.poetry]
name = "kyokusui"
version = "0.1.7"
description = ""
authors = ["boke0 <speken00.tt@gmail.com>"]
license = "MIT"

include = [
    "kyokusui/templates/*.html",
    "kyokusui/templates/**/*.html",
    "kyokusui/static/*",
    "kyokusui/static/**/*",
]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
unittest = "^0.0"
mitama = "^4.5.20"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = false
style = "pep440"
