[tool.poetry]
name = "terality"
version = "0.8.6"
description = "The Data Processing Engine for Data Scientists"
authors = ["Terality Engineering Team <dev.null@terality.com>"]
license = "Proprietary"
readme = "README.md"
homepage = "https://terality.com/"

[tool.poetry.dependencies]
python = "^3.7.1"
dill = "^0.3.2"
pyarrow = "^3.0.0"
numpy = "^1.18"
pandas = "^1.2.0"
requests = "^2.24.0"
aioboto3 = "^8.2.0"
pydantic = "^1.7.3"
aiobotocore = "^1.1"
backoff = "^1.10.0"

[tool.poetry.dev-dependencies]
mypy = "^0.790"
pytest = "^5.4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
