[tool.poetry]
name = "arcane-core"
version = "1.2.1"
description = "Common utility functions"
authors = ["Arcane <product@arcane.run>"]
packages = [
    { include = "arcane" }
]

[tool.poetry.dependencies]
python = "^3.6"
google-cloud-core = "^1.3"
typing-extensions = "^3.7.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
