[tool.poetry]
name = "twinthread"
version = "0.9.1"
description = ""
authors = ["Brent Baumgartner", "Brad Johnson", "James Howerton"]

[tool.poetry.dependencies]
python = "^3.6.1"
requests = "^2.23.0"
pandas = "^1.0.4"
azure-storage-blob = "^12.3.1"
requests_toolbelt = "^0.9.1"
simplejson = "^3.17.0"
plotly = "^4.8.1"
matplotlib = "^3.2.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
