[tool.poetry]
name = "izanami"
version = "1.1.8"
description = ""
authors = ["boke0 <speken00.tt@gmail.com>"]
license = "MIT"

include = [
    "izanami/templates/*.html",
    "izanami/templates/**/*.html",
    "izanami/static/*",
    "izanami/static/**/*",
]

[tool.poetry.dependencies]
python = "^3.6"
GitPython = "^3.1.13"
docker = "^4.4.4"
PyYAML = "^5.4.1"
unidiff = "^0.6.0"

[tool.poetry.dev-dependencies]
mitama = "^4.5.20"
unittest = "^0.0"
flake8 = "^3.8.4"
isort = "^5.7.0"
black = "^20.8b1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-dynamic-versioning]
enable = false
style = "pep440"
